# Generated by Django 4.2.7 on 2023-11-25 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_remove_pyseane_user_mdp_pyseane_user_last_login_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pyseane_user',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pyseane_user',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
    ]
